//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        public int IDDonDatPhong { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<int> accountID { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
