//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Tickets = new HashSet<Ticket>();
        }
        [DisplayName("ID")]
        public int flightID { get; set; }
        [DisplayName("Mã chuyến bay")]
        public string flightNumber { get; set; }
        [DisplayName("Điểm đi")]
        public string departureCity { get; set; }
        [DisplayName("Điểm đến")]
        public string arrivalCity { get; set; }
        [DisplayName("Thời gian xuất phát")]
        public System.DateTime departureTime { get; set; }
        [DisplayName("Thời gian đến")]
        public System.DateTime arrivalTime { get; set; }
        public Nullable<int> aircraftID { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
