//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketID { get; set; }
        public string ticketNumber { get; set; }
        public string seatNumber { get; set; }
        public decimal price { get; set; }
        public string status { get; set; }
        public Nullable<int> flightID { get; set; }
        public Nullable<int> passengerID { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
